using Marqdouj.DotNet.Web.JsInterop.Azure.Maps.Models.Spatial;
using Microsoft.JSInterop;
using System.Runtime.CompilerServices;

namespace Marqdouj.DotNet.Web.JsInterop.Azure.Maps.Interop.Modules
{
    /// <summary>
    /// Interface for Azure Maps spatial layer interactions.
    /// </summary>
    public interface IAzureMapsSpatialLayers
    {
        /// <summary>
        /// Adds a SimpleDataLayer to the map.
        /// </summary>
        /// <param name="mapId"></param>
        /// <param name="layer"></param>
        /// <param name="updateId">update the layer.Id with the result.id</param>
        /// <returns></returns>
        ValueTask<AddLayerResult> Add(string mapId, SimpleDataLayer layer, bool updateId = true);

        /// <summary>
        /// Adds SimpleDataLayers to the map.
        /// </summary>
        /// <param name="mapId"></param>
        /// <param name="layers"></param>
        /// <param name="updateId">update the layer.Id with the result.id</param>
        /// <returns></returns>
        ValueTask<List<AddLayerResult>> Add(string mapId, IEnumerable<SimpleDataLayer> layers, bool updateId = true);

        /// <summary>
        /// Gets the <see cref="SimpleDataLayerOptions"/> for a <see cref="SimpleDataLayer"/>
        /// </summary>
        /// <param name="mapId"></param>
        /// <param name="layerId"></param>
        /// <returns></returns>
        ValueTask<SimpleDataLayerOptions> GetOptions(string mapId, string layerId);

        /// <summary>
        /// Sets the options for a <see cref="SimpleDataLayer"/>.
        /// </summary>
        /// <param name="mapId"></param>
        /// <param name="layerId"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        ValueTask SetOptions(string mapId, string layerId, SimpleDataLayerOptions options);
    }

    internal class AzSpatialLayers(Lazy<Task<IJSObjectReference>> moduleTask) : IAzureMapsSpatialLayers
    {
        private readonly Lazy<Task<IJSObjectReference>> moduleTask = moduleTask;

        public async ValueTask<AddLayerResult> Add(string mapId, SimpleDataLayer layer, bool updateId = true)
        {
            var result = (await Add(mapId, [layer])).FirstOrDefault() ?? new AddLayerResult { InteropId = layer.Id };
            
            if (updateId && !string.IsNullOrWhiteSpace(result.Id))
                layer.Id = result.Id;

            return result;
        }

        public async ValueTask<List<AddLayerResult>> Add(string mapId, IEnumerable<SimpleDataLayer> layers, bool updateId = true)
        {
            var module = await moduleTask.Value;
            var dataLayers = layers.ToList();
            var results = await module.InvokeAsync<List<AddLayerResult>>(GetJsInteropMethod(), mapId, dataLayers) ?? [];

            if (updateId)
            {
                foreach (var result in results.Where(e => !string.IsNullOrWhiteSpace(e.Id)))
                {
                    var layer = dataLayers.FirstOrDefault(e => e.Id == result.InteropId);
                    layer?.Id = result.Id!;
                }
            }

            return results;
        }

        public async ValueTask<SimpleDataLayerOptions> GetOptions(string mapId, string layerId)
        {
            var module = await moduleTask.Value;
            return await module.InvokeAsync<SimpleDataLayerOptions>(GetJsInteropMethod(), mapId, layerId);
        }

        public async ValueTask SetOptions(string mapId, string layerId, SimpleDataLayerOptions options)
        {
            var module = await moduleTask.Value;
            await module.InvokeVoidAsync(GetJsInteropMethod(), mapId, layerId, options);
        }

        private static string GetJsInteropMethod([CallerMemberName] string name = "")
            => JsModule.SpatialLayers.GetJsModuleMethod(name);
    }

    /// <summary>
    /// The Spatial library does not allow assigning an id when creating a SimpleDataLayer; it generates an id internally.
    /// This result provides the internal id that was assigned to the layer. You will need this id if you want to work
    /// with the layer after it's been added.
    /// Recommened that you assign the internal id to the <see cref="SimpleDataLayer"/> id property once the layer is added.
    /// </summary>
    public class AddLayerResult
    {
        /// <summary>
        /// The <see cref="SimpleDataLayer"/> Id.
        /// </summary>
        public string? InteropId { get; set; }

        /// <summary>
        /// The internal id generated by the added layer.
        /// </summary>
        public string? Id { get; set; }

        /// <summary>
        /// Flag to indicate if an internal id was returned.
        /// </summary>
        public bool HasId => !string.IsNullOrWhiteSpace(Id);
    }
}
