<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>de229db3-3d9a-46bd-b757-a89c1ecb21f6</UserSecretsId>
  </PropertyGroup>

	<!--Ensure the XML documentation files are placed in the output folder-->
	<Target Name="_ResolveCopyLocalNuGetPackageXmls" AfterTargets="ResolveReferences">
		<ItemGroup>
			<ReferenceCopyLocalPaths Include="@(ReferenceCopyLocalPaths->'%(RootDir)%(Directory)%(Filename).xml')" Condition="Exists('%(RootDir)%(Directory)%(Filename).xml')" />
		</ItemGroup>
	</Target>
	
  <ItemGroup>
    <PackageReference Include="Marqdouj.DotNet.General.CsDoc" Version="10.6.4" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="5.0.0-rc.4-26180.1" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="5.0.0-rc.4-26180.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Marqdouj.DotNet.Web.JsInterop.Azure.Maps\Marqdouj.DotNet.Web.JsInterop.Azure.Maps.csproj" />
    <ProjectReference Include="..\Sandbox.Azure.Maps\Sandbox.Azure.Maps.csproj" />
    <ProjectReference Include="..\Sandbox.UI\Sandbox.UI.csproj" />
  </ItemGroup>
</Project>
